# Generated by Django 4.2.1 on 2023-06-08 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutpreference',
            options={'verbose_name': 'Workout', 'verbose_name_plural': 'Workouts'},
        ),
        migrations.AlterField(
            model_name='workoutpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutPreference', to=settings.AUTH_USER_MODEL),
        ),
    ]
