# Generated by Django 4.2.2 on 2023-07-14 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_workoutpreference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentlist',
            options={'verbose_name': 'equipment_list', 'verbose_name_plural': 'equipment_lists'},
        ),
        migrations.AlterModelOptions(
            name='workoutgoal',
            options={'verbose_name': 'goal', 'verbose_name_plural': 'goals'},
        ),
        migrations.AlterField(
            model_name='equipmentlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EquipmentsList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutgoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workoutGoals', to=settings.AUTH_USER_MODEL),
        ),
    ]
