# Generated by Django 4.2.1 on 2023-05-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_age_alter_user_height_alter_user_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PR_history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
