# Generated by Django 4.2.1 on 2023-05-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_pr_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(choices=[('A', 'Staying Healthy'), ('B', 'Lose Weight'), ('C', 'Tone Muscle'), ('D', 'Gain Muscle')], default='A'),
        ),
    ]
