# Generated by Django 4.2.7 on 2023-11-15 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.FloatField(blank=True)),
                ('calories', models.IntegerField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_parts', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('set_count', models.IntegerField(blank=True, default=0)),
                ('reps', models.IntegerField(blank=True, default=0)),
                ('weight', models.FloatField(blank=True, default=0)),
                ('rest_time', models.IntegerField(blank=True, default=0)),
                ('exercise_type', models.CharField(blank=True, max_length=50)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.workout')),
            ],
        ),
    ]
