# Generated by Django 4.1.1 on 2023-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='calories',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
