# Generated by Django 4.1.1 on 2023-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_workout_calories_alter_workout_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='calories',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.FloatField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
