# Generated by Django 4.1.1 on 2023-05-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_workout_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rest_time',
            field=models.DurationField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
